environment:

 matrix:    
    - PYTHON: "C:\\Python27\\"
      PYTHON_VERSION: "2.7.x" # currently 2.7.9
      PYTHON_ARCH: "32"
      PYTHON_DLL: "C:\\Windows\\SysWOW64\\python27.dll"      
      PYTHONPATH: "C:\\Python27\\Lib"
      PYTHONHOME: "C:\\Python27\\"
      
install:
-  call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86      
      
build_script:
 - python --version
 - nmake PYTHON_DLL=%PYTHON_DLL% PYTHON=%PYTHON%
  
artifacts:
- path: bin/release/*
  name: release  
